### PR TITLE
README Restore: drop and create db before piping into psql

### PR DESCRIPTION
**Pull request by schnittchen**

### CODE REVIEW

**Comment by SISheogorath** [comment]
Any details why?

I understand that this appears to be useful for full restore to a setup that already has data. But Then it's easier to delete the docker volume and start from scratch instead. But maybe you have some more insight into PostgreSQL than I have.

**Comment by schnittchen** [comment]
When the docker volume is started, all the migrations inserting tables are already done, so the previous backup step would show a lot of warnings for already existing objects.

This means that the backup sql script is replayed into a non-empty database with errors ignored. I am a bit afraid this might lead to subtle inconsistencies.

On the other side, the updated instructions work the way installing an SQL format backup is intended.

**Comment by SISheogorath** [comment]
Maybe then the docs are not clear enough. I would considering the import from the backup happens on a fresh database when CodiMD is not started. There you shouldn't see a error.

On a clean machine:

1. `docker-compose up -d database`
2. `cat backup.sql | docker exec -i $(docker-compose ps -q database) psql -U hackmd`

This shouldn't throw warnings.

**Comment by schnittchen** [comment]
I didn't know how to do that, thanks! In that case there should be a comment "Before running `docker-compose up` for starting for the first time, run these commands:".

I'll change accordingly.

**Comment by SISheogorath** [comment]
Awesome! Thanks!

**Comment by schnittchen** [comment]
For people coming here from the search engine:

Resetting to an entirely empty database can be done with

```
docker exec -i $(docker-compose ps -q database) dropdb -U hackmd hackmd
docker exec -i $(docker-compose ps -q database) createdb -U hackmd hackmd
```

**Pull request merged**
